routes/web.php
<?php

use App\Product;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $req) {
    $mainSlider = DB::table('slides')
        ->select()->orderBy('slide_number', 'asc')->get();
    $productsOnSlider = DB::table('products_on_slider')->get();
    $products = Product::all();
    $productSlider = [];
    foreach ($products as $product) {
        foreach ($productsOnSlider as $slide) {
            if ($product->id == $slide->product_id) {
                array_push($productSlider, $product);
            }
        }
    }
    return view('home', [
        'title' => 'Per Borup Design',
        'slider' => $mainSlider,
        'productsSlider' => $productSlider
    ]);
})->name('home');

Route::group(['prefix' => 'company', 'namespace'], function () {
    Route::get('about_us', function () {
        return view('company/about_us', ['title' => 'О нас']);
    });
    Route::get('history', function () {
        return view('company/history', ['title' => 'История бренда']);
    });
    Route::get('about_products', function () {
        return view('company/about_products', ['title' => 'Об изделиях']);
    });
    Route::get('production', function () {
        return view('company/production', ['title' => 'Изготовление']);
    });
    Route::get('partnership', function () {
        return view('company/partnership', ['title' => 'Сотрудничество']);
    });
    Route::get('contact_us', function () {
        return view('company/contact_us', ['title' => 'Связаться с нами']);
    });
});

Route::get('catalog', function () {
    return view('company/catalog', ['title' => 'Каталог']);
});

Route::get('instructions', function () {
    return view('company/instructions', ['title' => 'Полезные инструкциии']);
});

Route::get('shipping', function () {
    return view('company/shipping_returns', ['title' => 'Условие покупки, доставки и возврата']);
});
Route::get('store-policy', function () {
    return view('company/store_policy', ['title' => 'Политика конфиденциальности']);
});

Route::get('collections', function () {
    return view('collections/collections', ['title' => 'Коллекции']);
});

Route::get('stones', function () {
    return view('stones/stones', ['title' => 'Сменные камни']);
});

Route::get('podarki', function () {
    return view('target/target', ['title' => 'Повод']);
});

Route::group(['prefix' => 'store'], function () {
    Route::resource('/', 'StoreController');
    Route::post('/', 'StoreController@store');
    Route::get('product/{article}', 'StoreController@getProduct');
    Route::get('cart', 'CartController@cart');
    Route::get('cart/stone', 'CartController@cartStone');
    Route::get('order-success/{number}', 'OrderController@orderSuccess');
});

Route::group(['prefix' => 'account', 'middleware' => 'auth'], function () {
    Route::get('/my-account', 'AccountController@index');
    Route::get('/my-orders', 'AccountController@orders');
    Route::post('/avatar', 'AccountController@changeAvatar');
    Route::post('/update', 'AccountController@updateInfo');
});

Route::get('login', function () {
    abort(404);
});
Route::get('register', function () {
    abort(404);
});

Route::get('registration', function () {
    return view('registration', ['title' => 'Регистрация']);
});
Route::post('register', 'AuthController@register');
Route::post('login', 'AuthController@login');
Route::get('logout', 'Auth\LoginController@logout');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');

Route::group([
    'prefix' => 'password'
], function () {
    Route::post('create', 'PasswordResetController@create');
    Route::get('reset-password/{token}', 'PasswordResetController@find');
    Route::post('reset', 'PasswordResetController@reset');
});


Route::get('login/{provider}', 'AuthController@redirectToProvider');
Route::get('registration/{provider}', 'AuthController@handleProviderCallback');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['admin', 'auth']], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::get('/delete/product/{id}', 'ProductsController@deletProduct');
    Route::post('/order/products', 'ProductsController@changeOrder');
    Route::resource('/products', 'ProductsController');
    Route::resource('/collections', 'CollectionsController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/images', 'ImagesController');
    Route::resource('/users', 'UsersController');
    Route::resource('/orders', 'OrdersController');
    Route::resource('/targets', 'TargetsController');
    Route::resource('/materials', 'MaterialsController');
    Route::resource('/material-types', 'MaterialTypesController');
    Route::resource('/insertions', 'InsertionsController');
    Route::resource('/slider', 'SliderController');
    Route::get('/change-visible/{id}', 'ProductsController@changeVisible');
    Route::get('/deleteImage/{id}', 'ProductsController@deleteProductImage');
    Route::get('/add-to-slider/{id}', 'ProductsController@addToSlider');
    Route::post('/orders/complete', 'OrdersController@completeOrder');
    Route::post('/orders/payments', 'OrdersController@changePayments');
    Route::post('/orders/status', 'OrdersController@changeStatus');
});

Route::post('/subscriptions', 'CustomerController@subscribe');


Route::post('/add-to-cart', 'CartController@addToCart');
Route::get('/remove-from-cart/{tag}/{id}', 'CartController@removeFromCart');
Route::get('/get-cart-content', 'CartController@getCartContent');
Route::post('/update-cart', 'CartController@update');

Route::post('/feedback', 'CustomerController@sendMessage');
Route::post('/order', 'OrderController@makeOrder');
Route::get('/order', function () {
    abort(404);
});

resources/views/admin/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Панель администратора</title>
  <script src="https://kit.fontawesome.com/ba1cfbc415.js"></script>
  <link rel="dns-prefetch" href="//fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin.css') }}" rel="stylesheet">
</head>

<body>
  <div id="app" class='admin-template'>
    <nav class="navigation">
      <a class="navbar-brand" href="/">
        <img src="/images/logo.webp" width="80" height="40" alt="">
      </a>
      <?php
      $url = \Illuminate\Support\Facades\Route::current()->uri();
      ?>
      <ul class="navbar-nav">
        <li class="nav-item ">
          <a class="nav-link main-link {{$url === 'admin' ? 'active' : ''}}" href="{{ url('admin') }}">
            <i class="fas fa-home"></i>
            Главная
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link main-link {{$url === 'admin/orders' ? 'active' : ''}}" href="{{route('orders.index')}}">
            <i class="fas fa-shopping-cart"></i>
            Заказы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link main-link {{$url === 'admin/products' ? 'active' : ''}}" href="{{route('products.index')}}">
            <i class="far fa-gem"></i>
            Украшения
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link main-link {{$url === 'admin/users' ? 'active' : ''}}" href="{{route(('users.index'))}}">
            <i class="fas fa-users"></i>
            Пользователи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link main-link {{$url === 'admin/slider' ? 'active' : ''}}" href="{{route(('slider.index'))}}">
            <i class="fas fa-images"></i>
            Слайдер</a>
        </li>
        <div class="accordion" id="accordionExample">
          <div class="card sub-menu">
            <div id="headingOne sub-menu-header">
              <span class="mb-0">
                <button class="btn btn-link menu-btn" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Категории товаров <i class="fas fa-angle-down"></i>
                </button>
              </span>
            </div>
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
              <ul class="card-body sub-menu-list" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="nav-link main-link {{$url === 'admin/collections' ? 'active' : ''}}" href="{{route('collections.index')}}">Коллекции</a></li>
                <li><a class="nav-link main-link {{$url === 'admin/categories' ? 'active' : ''}}" href="{{route('categories.index')}}">Категории</a></li>
                <li><a class="nav-link main-link {{$url === 'admin/targets' ? 'active' : ''}}" href="{{route('targets.index')}}">Повод</a></li>
                <li><a class="nav-link main-link {{$url === 'admin/materials' ? 'active' : ''}}" href="{{route('materials.index')}}">Материалы</a></li>
                <li><a class="nav-link main-link {{$url === 'admin/material-types' ? 'active' : ''}}" href="{{route('material-types.index')}}">Типы материалов</a></li>
                <li><a class="nav-link main-link {{$url === 'admin/insertions' ? 'active' : ''}}" href="{{route('insertions.index')}}">Вставки</a></li>
              </ul>
            </div>
          </div>
        </div>
      </ul>
    </nav>
    <main class='content'>
      @yield('content')
    </main>
  </div>
  <script src="{{ asset('js/app.js') }}"></script>
  <script src="{{ asset('js/admin/admin.js') }}"></script>
  <script>
    $(document).ready(function() {
      $('#example').DataTable();
    });
  </script>

</body>

</html>

resources/views/admin/dashboard.blade.php
@extends('admin.admin')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="jumbotron">
          <p><span class="label label-primary">Покупателей: {{$customers}}</span></p>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="jumbotron">
          <p><span class="label label-primary">Украшений: {{$products}}</span></p>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="jumbotron">
          <p><span class="label label-primary">Посетителей 0</span></p>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="jumbotron">
          <p><span class="label label-primary">Сегодня 0</span></p>
        </div>
      </div>
    </div>

  </div>
@endsection

resources/views/admin/errors.blade.php
@if($errors->any())
    <div>
        @foreach($errors->all() as $error)
            <span class="badge badge-pill badge-danger">{{ $error }}</span>
        @endforeach
    </div>
@endif