routes/web.php
<?php

use App\Product;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $req) {
    $mainSlider = DB::table('slides')
        ->select()->orderBy('slide_number', 'asc')->get();
    $productsOnSlider = DB::table('products_on_slider')->get();
    $products = Product::all();
    $productSlider = [];
    foreach ($products as $product) {
        foreach ($productsOnSlider as $slide) {
            if ($product->id == $slide->product_id) {
                array_push($productSlider, $product);
            }
        }
    }
    return view('home', [
        'title' => 'Per Borup Design',
        'slider' => $mainSlider,
        'productsSlider' => $productSlider
    ]);
})->name('home');

Route::group(['prefix' => 'company', 'namespace'], function () {
    Route::get('about_us', function () {
        return view('company/about_us', ['title' => 'О нас']);
    });
    Route::get('history', function () {
        return view('company/history', ['title' => 'История бренда']);
    });
    Route::get('about_products', function () {
        return view('company/about_products', ['title' => 'Об изделиях']);
    });
    Route::get('production', function () {
        return view('company/production', ['title' => 'Изготовление']);
    });
    Route::get('partnership', function () {
        return view('company/partnership', ['title' => 'Сотрудничество']);
    });
    Route::get('contact_us', function () {
        return view('company/contact_us', ['title' => 'Связаться с нами']);
    });
});

Route::get('catalog', function () {
    return view('company/catalog', ['title' => 'Каталог']);
});

Route::get('instructions', function () {
    return view('company/instructions', ['title' => 'Полезные инструкциии']);
});

Route::get('shipping', function () {
    return view('company/shipping_returns', ['title' => 'Условие покупки, доставки и возврата']);
});
Route::get('store-policy', function () {
    return view('company/store_policy', ['title' => 'Политика конфиденциальности']);
});

Route::get('collections', function () {
    return view('collections/collections', ['title' => 'Коллекции']);
});

Route::get('stones', function () {
    return view('stones/stones', ['title' => 'Сменные камни']);
});

Route::get('podarki', function () {
    return view('target/target', ['title' => 'Повод']);
});

Route::group(['prefix' => 'store'], function () {
    Route::resource('/', 'StoreController');
    Route::post('/', 'StoreController@store');
    Route::get('product/{article}', 'StoreController@getProduct');
    Route::get('cart', 'CartController@cart');
    Route::get('cart/stone', 'CartController@cartStone');
    Route::get('order-success/{number}', 'OrderController@orderSuccess');
});

Route::group(['prefix' => 'account', 'middleware' => 'auth'], function () {
    Route::get('/my-account', 'AccountController@index');
    Route::get('/my-orders', 'AccountController@orders');
    Route::post('/avatar', 'AccountController@changeAvatar');
    Route::post('/update', 'AccountController@updateInfo');
});

Route::get('login', function () {
    abort(404);
});
Route::get('register', function () {
    abort(404);
});

Route::get('registration', function () {
    return view('registration', ['title' => 'Регистрация']);
});
Route::post('register', 'AuthController@register');
Route::post('login', 'AuthController@login');
Route::get('logout', 'Auth\LoginController@logout');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');

Route::group([
    'prefix' => 'password'
], function () {
    Route::post('create', 'PasswordResetController@create');
    Route::get('reset-password/{token}', 'PasswordResetController@find');
    Route::post('reset', 'PasswordResetController@reset');
});


Route::get('login/{provider}', 'AuthController@redirectToProvider');
Route::get('registration/{provider}', 'AuthController@handleProviderCallback');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['admin', 'auth']], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::get('/delete/product/{id}', 'ProductsController@deletProduct');
    Route::post('/order/products', 'ProductsController@changeOrder');
    Route::resource('/products', 'ProductsController');
    Route::resource('/collections', 'CollectionsController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/images', 'ImagesController');
    Route::resource('/users', 'UsersController');
    Route::resource('/orders', 'OrdersController');
    Route::resource('/targets', 'TargetsController');
    Route::resource('/materials', 'MaterialsController');
    Route::resource('/material-types', 'MaterialTypesController');
    Route::resource('/insertions', 'InsertionsController');
    Route::resource('/slider', 'SliderController');
    Route::get('/change-visible/{id}', 'ProductsController@changeVisible');
    Route::get('/deleteImage/{id}', 'ProductsController@deleteProductImage');
    Route::get('/add-to-slider/{id}', 'ProductsController@addToSlider');
    Route::post('/orders/complete', 'OrdersController@completeOrder');
    Route::post('/orders/payments', 'OrdersController@changePayments');
    Route::post('/orders/status', 'OrdersController@changeStatus');
});

Route::post('/subscriptions', 'CustomerController@subscribe');


Route::post('/add-to-cart', 'CartController@addToCart');
Route::get('/remove-from-cart/{tag}/{id}', 'CartController@removeFromCart');
Route::get('/get-cart-content', 'CartController@getCartContent');
Route::post('/update-cart', 'CartController@update');

Route::post('/feedback', 'CustomerController@sendMessage');
Route::post('/order', 'OrderController@makeOrder');
Route::get('/order', function () {
    abort(404);
});

app/Http/Controllers/Admin/MaterialTypesController.php
<?php

namespace App\Http\Controllers\admin;

use App\Material;
use App\MaterialType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class MaterialTypesController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $materials = MaterialType::all();
    return view('admin.materialTypes.index',
      [
        'materials' => $materials,

      ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $parentMaterials = Material::all();
    return view('admin.materialTypes.create', [
      'parentMaterials' => $parentMaterials
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'name' => 'required|string',
      'color' => 'required',
      'material_id' => 'required|numeric'
    ]);
    MaterialType::create($request->all());
    return response()->json('ok');
  }

  /**
   * Display the specified resource.
   *
   * @param  int $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $material =  MaterialType::find($id);
    $parentMaterials = Material::all();
    return view('admin.materialTypes.edit',
      [
        'material' => $material,
        'parentMaterials' => $parentMaterials
      ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request $request
   * @param  int $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $this->validate($request, [
      'name' => 'required|string',
      'color' => 'required',
      'material_id' => 'required|numeric'
    ]);
    $material = MaterialType::find($id);
    $material->name = $request->name;
    $material->color = $request->color;
    $material->material_id = $request->material_id;
    try {
      $material->save();
      return response()->json('ok');
    } catch (\Exception $error) {
      Log::error($error->getMessage());
      return abort('404');
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    MaterialType::find($id)->delete();
    return redirect()->route('material-types.index');
  }
}

resources/views/admin/materialTypes/create.blade.php
@extends('admin.admin')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-12">
        <h2>Добавьте новый тип материала</h2>
        <hr class="mb-5"/>
        @if($errors->any())
          <div class="container">
            <div class="row">
              <div class="col-md-10 offset-1">
                @foreach($errors->all() as $error)
                  <div class="alert alert-danger" role="alert">
                    {{$error}}
                  </div>
                @endforeach
              </div>
            </div>
          </div>
        @endif
        <create-material
            :parent="{{json_encode($parentMaterials)}}"
        ></create-material>
      </div>
    </div>
  </div>
  </div>
@endsection

resources/views/admin/materialTypes/edit.blade.php
@extends('admin.admin')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-12">
        <h2>Измените тип материала {{$material->name}}</h2>
        <hr class="mb-5"/>
        @if($errors->any())
          <div class="container">
            <div class="row">
              <div class="col-md-10 offset-1">
                @foreach($errors->all() as $error)
                  <div class="alert alert-danger" role="alert">
                    {{$error}}
                  </div>
                @endforeach
              </div>
            </div>
          </div>
        @endif
        <edit-material
            :material="{{json_encode($material)}}"
            :parent="{{json_encode($parentMaterials)}}"
        >
        </edit-material>
      </div>
    </div>
  </div>
  </div>
@endsection

resources/views/admin/materialTypes/index.blade.php
@extends('admin.admin')

@section('content')
  <a href="{{route('material-types.create')}}" class="btn btn-dark pull-right mb-3">Добавить тип материалa</a>
  <table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
    <tr>
      <th>id</th>
      <th>Название</th>
      <th>Цвет</th>
      <th>Редактировать</th>
    </tr>
    </thead>
    <tbody>
    @forelse($materials as $material)
      <tr>
        <td>{{$material->id}}</td>
        <td>{{$material->name}}</td>
        <td style="background-color: {{$material->color}}"></td>
        <td>
          <div class="container">
            <div class="row">
              <a href="{{route('material-types.edit', $material->id)}}"><i class="fas fa-edit"></i></a>
              {!! Form::open(['route' => ['material-types.destroy', $material->id], 'method' => 'delete']) !!}
              <button type="submit" style="border: none; color: #1f6fb2; background-color: transparent; outline: none;"
                      class="btn  btn-sm" onclick="return  confirm('Удалить материал?')"><i class="fas fa-trash"></i>
              </button>
              {!! Form::close() !!}
            </div>
          </div>
        </td>
      </tr>
    @empty
      <td colspan="7" class="text-center"><h3>Материалов нет</h3></td>
    @endforelse
    </tbody>

  </table>

@endsection